### PR TITLE
Translation of README.md Chinese

### PR DESCRIPTION
**Pull request by zigerZZZ**
I translate it when I'm learning this

### CODE REVIEW

**Comment by sgrvinod** [comment]
Hi @zigerZZZ, thank you very much.

**Comment by sgrvinod** [comment]
I have made a note on the English README that your translation is available.

**Comment by sgrvinod** [comment]
@zigerZZZ  Please let me know if my note is incorrect. Is it correct to say "Chinese translation" or is it a specific form of Chinese language?

**Comment by zigerZZZ** [comment]
@sgrvinod Sure, that's the correct form.Or you can explain it with "中文翻译", as Chinese characters are more likely to catch their eyes who speaking Chinese

**Comment by sgrvinod** [comment]
Thanks, I added it.

**Pull request merged**
